import fs from 'node:fs';
import {save,shell,pageIntro,A,esc,socials,links,origin} from './templates.mjs';
import './home.mjs';
const read=file=>JSON.parse(fs.readFileSync('content/'+file+'.json','utf8'));
const stories=read('stories');
const pubLinks=p=>p.papers.length?`<div class="publication-links"><span class="small-label">For the curious (and the technically curious)</span>${p.papers.map(([doi,label])=>A('https://doi.org/'+doi,esc(label))).join('')}</div>`:'';
const storyBody=p=>`<p class="opening">${esc(p.opening)}</p><div class="body-copy">${p.body.map(t=>`<p>${esc(t)}</p>`).join('')}</div>${pubLinks(p)}`;
const entries=stories.map((p,i)=>`<article class="project-story" id="${p.id}"><div class="project-number">0${i+1}</div><div><span class="small-label">${esc(p.label)}</span><h2>${esc(p.title)}</h2><span class="project-status">${esc(p.status)}</span>${storyBody(p)}</div><aside class="aside"><span class="small-label">What stayed with me</span><p>${esc(p.lesson)}</p></aside></article>`).join('');
const upcoming=`<section id="in-progress" class="spaced"><div class="page-intro"><span class="small-label">Still in the notebook</span><h2>Two more stories are on their way.</h2><p class="lead">Some work needs a little more time before it can leave the lab.</p></div><div class="upcoming-grid"><article class="upcoming"><span class="project-status">Unpublished work</span><h2>A closer look at solar cells.</h2><p><strong>TEM–CL photovoltaics.</strong> My ongoing work brings together electron microscopy and cathodoluminescence—light emitted when a material is excited by electrons—to look at photovoltaic materials.</p><p>The full story, including my contribution, methods, and results, will follow when the research is ready to share.</p></article><article class="upcoming"><span class="project-status">Under review</span><h2>Listening to a material in more than one way.</h2><p><strong>Multimodal spectroscopy.</strong> Different measurements can offer different clues about the same material. This project brings that idea into my spectroscopy work.</p><p>The manuscript is under review. I’ll share the details and what I learned when it becomes public.</p></article></div></section>`;
save('/projects/','A few things I’ve been working on','The questions, my contributions, and lessons from lasers, recycling, automation, crystal growth, thin films, and imaging.',pageIntro('A peek inside my notebook','A few things I’ve<br>been working on.','Here’s what made me curious, what I did about it, and what I learned along the way. There are papers if you want the details. You won’t need them to follow the story.')+`<div class="wrap"><div class="project-index">${stories.map(p=>A('#'+p.id,p.label)).join('')}${A('#in-progress','Work in progress')}</div>${entries}${upcoming}<div class="notebook"><h3>Prefer the references?</h3><p>${A('/publications/','The complete publication list')} lives here. The stories above are my less formal version.</p></div></div>`);
const docs=read('documents');
save('/documents/','Resume & CV','Mahantesh Khetri’s resume and academic CV.',pageIntro('For the practical details','The short version.<br>And the longer one.','A handy place for the PDFs, without making you collect the details from every page.')+`<div class="wrap"><div class="document-grid">${docs.map(d=>`<article class="document"><span class="small-label">PDF</span><h2>${esc(d.title)}</h2><p>${esc(d.description)}</p>${d.file?A(d.file,'Download '+esc(d.title),'text-link'):'<span class="status">Updated PDF coming soon.</span>'}</article>`).join('')}</div><div class="notebook"><p>Need a copy in the meantime? ${A(links.email,'Send me a note')} and I’ll be happy to share one.</p></div></div>`);
await import('./gallery.mjs');
const awards=[
 ['2025–2026','Wilson Bicentennial Graduate Fellowship','University of Virginia','Support for my doctoral research in laser processing and materials recovery.','A welcome vote of confidence for the next experiment.'],
 ['2025','First place, Electrical Engineering poster','UVA Engineering Research Symposium','For work on laser-assisted silver recycling and AI-driven process automation.','Turns out the poster was worth all that rearranging.'],
 ['2025','Second place, invited speaker presentation','UVA Engineering Research Symposium','Recognition for presenting my doctoral research.','A good reason to keep practicing the short explanation.'],
 ['2025','UPLAMP travel award','Vilnius, Lithuania','Support to attend the summer school on ultra-short pulse laser applications in materials processing.','Learning about lasers came with a change of scenery.'],
 ['2024','NSF-supported ANGEL-7 travel award','Charlottesville, Virginia','Support for the conference and tutorial on laser-generated nanoparticles.','More questions came home with me.'],
 ['2019–2022','Institute Fellowship','IIT Delhi','Research fellowship support during my time in the Department of Physics.','Time and support to keep learning by doing.'],
 ['2017–2019','Merit-cum-Means Scholarship','IIT Ropar','Scholarship support during my MSc in Physics.','An important step in a much longer journey.'],
 ['2016','University Second Rank & Gold Medal in Computer Science','Rani Channamma University','Recognition during my BSc in Computer Science, Physics, and Mathematics.','An early milestone that still means a lot.']
];
save('/awards/','A few proud moments','Fellowships, awards, scholarships, and achievements along Mahantesh Khetri’s journey.',pageIntro('Since you clicked…','A few proud moments.','If you’ve made it to this page, I’m taking that as permission to be a little proud. These awards mean a lot to me—and on a difficult research day, they’re a helpful nudge to keep going.')+`<div class="wrap"><div class="milestones">${awards.map(([year,title,where,desc,human])=>`<article class="milestone"><span class="when">${year}</span><div><h2>${title}</h2><p><strong>${where}</strong><br>${desc}</p></div><p class="human">${human}</p></article>`).join('')}</div><p class="subtle spaced">None of this happened alone. I’m grateful to the teachers, mentors, collaborators, and family who helped me get here.</p></div>`);
await import('./community.mjs');
let pubs=read('publications');
if(!pubs.some(p=>p.doi==='10.1007/s43538-022-00101-5'))pubs.push({id:8,title:'Electrochemical investigation of MoSeTe as an anode for sodium-ion batteries',authors:'Priya Mudgal, Himani Arora, Jayashree Pati, Manish K. Singh, Mahantesh Khetri, Rajendra S. Dhaka',role:'Co-author',journal:'Proceedings of the Indian National Science Academy',year:'2022',doi:'10.1007/s43538-022-00101-5'});
pubs.sort((a,b)=>Number(b.year)-Number(a.year));
save('/publications/','Publications','Published research by Mahantesh Khetri and collaborators.',pageIntro('The references','For the full details.','The papers behind some of the stories. For the less formal version, head back to '+A('/projects/','Projects')+'.')+`<div class="wrap spaced">${pubs.map(p=>`<article class="pub-row"><div class="pub-year">${p.year}<br><span class="subtle">${p.role}</span></div><div><h2>${A('https://doi.org/'+p.doi,esc(p.title))}</h2><p>${esc(p.authors)}</p><p><em>${esc(p.journal)}</em> · ${A('https://doi.org/'+p.doi,'Publisher / DOI')}</p></div></article>`).join('')}<div class="notebook"><span class="small-label">Published patent application · Co-inventor</span><h3>Use of Lasers to Selectively Remove Materials from Substrates</h3><p>Mool C. Gupta and Mahantesh Khetri · US20260008129A1</p>${A('https://patents.google.com/patent/US20260008129A1/en','Read the patent application')}</div></div>`);
const legacy={ 'silver-recovery-silicon':'recycling','pv-backsheet-delamination':'recycling','machine-vision-laser-automation':'recycling','silver-recovery-cigs':'recycling','thin-film-materials':'crystals','transparent-conducting-oxides':'thin-films'};
for(const [slug,id] of Object.entries(legacy)){const p=stories.find(s=>s.id===id);save('/projects/'+slug+'/',p.title,p.opening,pageIntro(p.label,p.title,p.opening)+`<div class="wrap"><div class="detail-copy"><p class="breadcrumbs">${A('/projects/#'+id,'Back to the project stories')}</p>${p.body.map(t=>`<p>${esc(t)}</p>`).join('')}<h2>What stayed with me</h2><p>${esc(p.lesson)}</p>${pubLinks(p)}</div></div>`)}
const routes=['/','/projects/','/documents/','/gallery/','/awards/','/community/','/publications/',...Object.keys(legacy).map(k=>'/projects/'+k+'/')];
if(origin)fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>${origin}${r}</loc></url>`).join('')+'</urlset>');
else if(fs.existsSync('dist/sitemap.xml'))fs.unlinkSync('dist/sitemap.xml');
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\n${origin?'Sitemap: '+origin+'/sitemap.xml\n':''}`);
fs.writeFileSync('dist/404.html',shell('This page wandered off','Return to Mahantesh Khetri’s home page.','/404.html',pageIntro('A small detour','This page wandered off.','Let’s get you '+A('/','back home')+'.')));
console.log('Built home, projects, documents, gallery, awards, community, publications and preserved project routes.');
