import fs from 'node:fs';
export const origin=(process.env.SITE_URL||'').replace(/\/$/,'');
export const basePath=(process.env.BASE_PATH||'').replace(/\/$/,'');
if(basePath && !/^\/[a-zA-Z0-9_./-]+$/.test(basePath))throw new Error('Invalid BASE_PATH');
if(origin && !/^https?:\/\//.test(origin))throw new Error('SITE_URL must be an absolute URL');
const portable=html=>html.replace(/(href|src|data-photo)="\/(?!\/)/g,(_,attr)=>attr+'="'+basePath+'/');
export const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const A=(url,text,cls='')=>`<a class="${cls}" href="${esc(url)}">${text}</a>`;
export const links={linkedin:'https://www.linkedin.com/in/mahantesh-khetri-301154118/',scholar:'https://scholar.google.com/citations?user=z0M8wTUAAAAJ&hl=en',lab:'https://engineering.virginia.edu/labs-groups/laser/people',email:'mailto:mahanteshkhetri@gmail.com'};
export const socials=()=>`<div class="socials">${A(links.linkedin,'LinkedIn')}${A(links.scholar,'Google Scholar')}${A(links.lab,'My lab')}${fs.existsSync('content/social.json')&&JSON.parse(fs.readFileSync('content/social.json','utf8')).instagram?A(JSON.parse(fs.readFileSync('content/social.json','utf8')).instagram,'Instagram'):''}${A(links.email,'Say hello')}</div>`;
const menu=[['/','Home'],['/projects/','Projects'],['/documents/','Resume & CV'],['/awards/','Awards'],['/community/','Giving back'],['/gallery/','Gallery']];
export function shell(title,desc,route,body){return portable(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f7f6f2"><title>${esc(title)} | Mahantesh Khetri</title><meta name="description" content="${esc(desc)}">${origin?`<link rel="canonical" href="${origin}${route}">`:""}<meta property="og:title" content="${esc(title)} | Mahantesh Khetri"><meta property="og:description" content="${esc(desc)}">${origin?`<meta property="og:url" content="${origin}${route}">`:""}<meta property="og:type" content="website">${route==='/'&&origin?`<meta property="og:image" content="${origin}/assets/social.png"><meta name="twitter:card" content="summary_large_image">`:''}<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='16' fill='%231a3147'/%3E%3Ctext x='4' y='22' fill='%23f7f6f2' font-family='Georgia' font-size='17'%3Emk%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><div class="wrap navigation">${A('/','mahantesh<span class="brand-dot">.</span>','brand')}<button class="menu-toggle" aria-expanded="false" aria-controls="nav">Menu</button><nav id="nav" aria-label="Main navigation">${menu.map(([url,t])=>`<a href="${url}" ${route===url?'aria-current="page"':''}>${t}</a>`).join('')}</nav></div></header><main id="main">${body}</main><footer><div class="wrap footer-top"><div><span class="footer-name">Mahantesh Khetri</span><p>Charlottesville, Virginia.<br>Usually somewhere between a question and an experiment.</p></div><div><span class="small-label">Find me elsewhere</span>${socials()}</div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Mahantesh Khetri</span>${A('/publications/','The full publication list')}</div></footer></body></html>`);}
export function save(route,title,desc,body){const dest=route==='/'?'dist':'dist'+route;fs.mkdirSync(dest,{recursive:true});fs.writeFileSync(dest+'/index.html',shell(title,desc,route,body));}
export const pageIntro=(eyebrow,title,desc)=>`<div class="page-intro wrap"><span class="small-label">${eyebrow}</span><h1>${title}</h1><p class="lead">${desc}</p></div>`;
